steps:
  # Docker Build
  - name: 'infra-project-repo'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/radiant-octane-405301/cloud_infra_group_projectt-main-result/${SHORT_SHA}', '.']
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/radiant-octane-405301/cloud_infra_group_projectt-main-result/${SHORT_SHA}']
 
# setup cloud sdk
  - name: 'infra-project-repo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy infra-cloudrun-service --image=us-central1-docker.pkg.dev/radiant-octane-405301/cloud_infra_group_projectt-main-result/${SHORT_SHA} --platform=managed --region=us-central1 --port=5001

#2

steps:
  # Docker Build
  - name: 'infra-project-repo'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/radiant-octane-405301/cloud_infra_group_projectt-main-vote/${SHORT_SHA}', '.']
  # Docker Push
  - name: 'infra-project-repo'
    args: ['push', 'us-central1-docker.pkg.dev/radiant-octane-405301/cloud_infra_group_projectt-main-vote/${SHORT_SHA}']
 
# setup cloud sdk
  - name: 'infra-project-repo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy infra-cloudrun-service1 --image=us-central1-docker.pkg.dev/radiant-octane-405301/cloud_infra_group_projectt-main-vote/${SHORT_SHA} --platform=managed --region=us-central1 --port=5000
